export const defaultSettings = {
    wallpaperFolderPath: "",
    wallpaperFrequency: 1,
    filterColor: "#000000",
    filterOpacity: 0.3,
    iconSize: 28,
    iconSpacing: 8,
    iconGap: 8,
    categoryGap: 12,
    bookmarkMinWidth: 150,
    iconBorderRadius: 8,
    iconBorderColor: "#697c96",
    iconBgColor: "#7491b9",
    iconBgOpacity: 0.75,
    bookmarkFontFamily: "sans-serif",
    bookmarkFontSize: 12,
    bookmarkFontColor: "#e2e8f0",
    nameDisplay: "always",
    textBehavior: "truncate",
    iconLayout: "row",
    themePreset: "dark",
    layoutMode: "list",
    columnCount: 3,
    sidebarWidth: 240,
    quickLinksSize: 13,
    sectionPadding: 15,
    sectionBgColor: "#43587a",
    sectionBgOpacity: 0.55,
    sectionLineColor: "#7d3af8",
    clockStyle: "analog",
    userName: "",
    weatherCity: "",
    wallpaperSource: "unsplash",
    wallpaperTheme: "nature",
    wallpaperApiKey: "",
    togglApiToken: "",
    pomodoroEnabled: false,
    pomodoroWork: 25,
    pomodoroBreak: 5
};

export const defaultCustomIcons = {};

